title: Restaurante Tia Maria
email: info@restaurantetiamaria.com
description: >- # this means to ignore newlines until "baseurl:"
  Catering & Eventos
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author: Ivo Zinenda

# Build settings
plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

collections_dir: collection
collections:
  slider:
  sobre:
  servicos:
  menu:
  eventos:

# Assets
sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/TiaMariaLogotipo.svg
logo: /assets/img/TiaMariaLogo.svg
color: "#e71d02"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
