backend:
  name: git-gateway
  use_large_media_transforms_in_media_library: false

media_folder: 'assets/uploads'

logo_url: 'https://d33wubrfki0l68.cloudfront.net/f1afd154dd1bd09e6957dce7291bfc56834b4489/b2edb/assets/img/brand/logo.svg'

collections:

  - label: "Sobre"
    name: "sobre"
    folder: "collections/_sobre"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Descrição", name: "body", widget: "markdown"}

  - label: "Serviços"
    name: "servicos"
    folder: "collections/_servicos"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Ícones", name: "icon", widget: "string"}
      - {label: "Descrição", name: "body", widget: "markdown"}

  - label: "Prato do Dia"
    name: "prato-do-dia"
    folder: "collections/_prato-do-dia"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Dia da Semana", name: "publish-day", widget: "string"}
      - {label: "Prado do Dia", name: "publish", widget: "boolean", default: "false"}
      - {label: "Preço", name: "price", widget: "number"}

  - label: "Menu - Restaurante"
    name: "restaurante"
    folder: "collections/_restaurante"
    create: true
    fields:
      - {label: "Prato", name: "title", widget: "string"}
      - label: "Tipos de Pratos"
        name: "category"
        widget: "select"
        options: ["Entradas", "Acompanhamentos", "Carnes", "Mariscos", "Peixes", "Sobremesas", "Sandes"]
      - {label: "Preço", name: "price", widget: "number"}

  - label: "Menu - Bar"
    name: "bar"
    folder: "collections/_bar"
    create: true
    fields:
      - {label: "Bibida", name: "title", widget: "string"}
      - label: "Tipo de Bebida"
        name: "category"
        widget: "select"
        options: ["Cerveja", "Refrigerantes", "Chá & Café"]
      - {label: "Preço", name: "price", widget: "number"}

  - label: "Menu - Bebidas"
    name: "bebida"
    folder: "collections/_bebidas"
    create: true
    fields:
      - {label: "Bibida", name: "title", widget: "string"}
      - label: "Tipo de Bebida"
        name: "category"
        widget: "select"
        options: ["Whiskey", "Gin", "Cachaça", "Vodka", "Amarula", "Vinhos"]
      - {label: "Preço", name: "price", widget: "number"}
      - {label: "Shots", name: "shot", widget: "boolean", default: true, required: false}
      - {label: "Preço do shot/taça", name: "shotprice", widget: "number", required: false}


  - label: "Eventos"
    name: "eventos"
    folder: "collections/_eventos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: Nome do Evento", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Capa do Evento", name: "image-cover", widget: "image"}