backend:
  name: git-gateway
  use_large_media_transforms_in_media_library: false

media_folder: 'assets/uploads'

logo_url: 'https://d33wubrfki0l68.cloudfront.net/f1afd154dd1bd09e6957dce7291bfc56834b4489/b2edb/assets/img/brand/logo.svg'

collections:
  - label: "Prato do Dia"
    name: "prato-do-dia"
    folder: "collections/_prato-do-dia"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Dia da Semana", name: "publish-day", widget: "string"}
      - {label: "Prado do Dia", name: "publish", widget: "boolean", default: "false"}
      - {label: "Preço", name: "price", widget: "number", valueType: "float"}

  - label: "Menu"
    name: "menu"
    folder: "collections/_menu"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - label: "Tipos de Pratos"
        name: "category"
        widget: "select"
        options: ["Entradas", "Bebidas", "Pratos", "Pizzas", "Saladas", "Sobremesas", "Sandes"]
      - {label: "Preço", name: "price", widget: "number", valueType: "float"}

  - label: "Eventos"
    name: "eventos"
    folder: "collections/_eventos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: Nome do Evento", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Capa do Evento", name: "image-cover", widget: "image"}

  - label: "Galeria"
    name: "galeria"
    folder: "collections/_galeria"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: Nome do Evento", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Capa do Evento", name: "image-cover", widget: "image"}
      - label: "Fotos"
        name: "photos"
        widget: "list"
        field: 
          - {label: "Foto", name: "photo", widget: "image"}